# This uses the various SingleCellExperiment objects generated by the simpleSingleCell workflow.
# Follow the instructions at http://bioconductor.org/packages/devel/workflows/html/simpleSingleCell.html to run the workflows.

library(scater)
fpath <- "../../../simpleSingleCell/package/vignettes"

# Computing the pseudo count and maximum for each data set.

pseudos <- list()
countsizes <- list()

for (object in c("pbmc_data.rds", "brain_data.rds", "416B_data.rds")) {
    sce <- readRDS(file.path("../../../simpleSingleCell/package/vignettes", object))
    size.facs <- sizeFactors(sce)
    big.pseudo <- abs(1/quantile(size.facs, 0.05) - 1/quantile(size.facs, 0.95))

    prefix <- sub("_data.rds", "", object)
    pseudos[[prefix]] <- big.pseudo
    countsizes[[prefix]] <- sum(calcAverage(counts(sce), use_size_factors=size.facs) > big.pseudo)
}

pseudos
countsizes
